# Generated by Django 4.2.7 on 2025-09-07 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("challenges", "0003_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembershiplog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_team_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teammembershiplog",
            name="team",
            field=models.ForeignKey(
                help_text="Team involved",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_logs",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teammembershiplog",
            name="user",
            field=models.ForeignKey(
                help_text="User involved",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_membership_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="team",
            field=models.ForeignKey(
                help_text="Team the user wants to join",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="user",
            field=models.ForeignKey(
                help_text="User requesting to join",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_join_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who sent the invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_team_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="team",
            field=models.ForeignKey(
                help_text="Team sending the invitation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="user",
            field=models.ForeignKey(
                help_text="User being invited",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamchallengesolve",
            name="challenge",
            field=models.ForeignKey(
                help_text="Challenge that was solved",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_solves",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="teamchallengesolve",
            name="solved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Team member who submitted the correct flag",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_solves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamchallengesolve",
            name="team",
            field=models.ForeignKey(
                help_text="Team that solved the challenge",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_solves",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                help_text="Team avatar",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="users.avataroption",
                verbose_name="avatar",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="captain",
            field=models.OneToOneField(
                blank=True,
                help_text="Team captain/leader",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captain_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamjoinrequest",
            unique_together={("team", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="teaminvite",
            unique_together={("team", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="teamchallengesolve",
            unique_together={("team", "challenge")},
        ),
    ]
