# DCTFd - A Capture The Flag platform built with Django
# Developed by Srivatsan Sk
# MIT License - Copyright (c) 2025 Srivatsan Sk

services:
  web:
    build: .
    restart: always
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
    environment:
      # Default environment variables if .env file is not present
      - DJANGO_ENVIRONMENT=${DJANGO_ENVIRONMENT:-production}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-oiwul3d$hyc=d=z_%04=fj=$n46!d!x$bj*ns+k#)g^qhicbi@}
      - DEBUG=${DEBUG:-False}
      - DEV_MODE=${DEV_MODE:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - EVENT_NAME=${EVENT_NAME:-Section 13(September Edition)}
      # Default database configuration
      - DB_NAME=${DB_NAME:-dctfd_db}
      - DB_USER=${DB_USER:-dctfd_user}
      - DB_PASSWORD=${DB_PASSWORD:-dctfd_postgres_password}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DATABASE_URL=${DATABASE_URL:-postgres://${DB_USER:-dctfd_user}:${DB_PASSWORD:-dctfd_postgres_password}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-dctfd_db}}
      # Email settings
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-True}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@dctfd.com}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: gunicorn DCTFd.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-dctfd_postgres_password}
      - POSTGRES_USER=${DB_USER:-dctfd_user}
      - POSTGRES_DB=${DB_NAME:-dctfd_db}
      # Default PostgreSQL configuration
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD:-md5}
      # Performance tuning (adjust based on your host's resources)
      - POSTGRES_MAX_CONNECTIONS=${POSTGRES_MAX_CONNECTIONS:-100}
      - POSTGRES_SHARED_BUFFERS=${POSTGRES_SHARED_BUFFERS:-128MB}
      - POSTGRES_WORK_MEM=${POSTGRES_WORK_MEM:-4MB}
      - POSTGRES_EFFECTIVE_CACHE_SIZE=${POSTGRES_EFFECTIVE_CACHE_SIZE:-512MB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-dctfd_user} -d ${DB_NAME:-dctfd_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
