# Generated by Django 4.2.7 on 2025-09-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbadge",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Event during which the badge was earned (if any)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awarded_badges",
                to="event.event",
            ),
        ),
    ]
