# Generated by Django 4.2.7 on 2025-09-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreboardentry",
            name="team",
            field=models.ForeignKey(
                help_text="Team this entry represents",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoreboard_entries",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="scoreboard",
            name="event",
            field=models.OneToOneField(
                help_text="Event this scoreboard belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoreboard",
                to="event.event",
            ),
        ),
        migrations.AddField(
            model_name="eventsettings",
            name="event",
            field=models.OneToOneField(
                help_text="Event these settings belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="event.event",
            ),
        ),
    ]
