# Generated by Django 4.2.7 on 2025-09-07 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event", "0002_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this registration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                help_text="Event being registered for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="event.event",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team registering for the event (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_event_registrations",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="user",
            field=models.ForeignKey(
                help_text="User registering for the event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_event_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="event",
            field=models.ForeignKey(
                help_text="Event this page belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="event.event",
            ),
        ),
        migrations.AddField(
            model_name="eventannouncement",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this announcement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_event_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventannouncement",
            name="event",
            field=models.ForeignKey(
                help_text="Event this announcement belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="event.event",
            ),
        ),
        migrations.AddField(
            model_name="eventactivity",
            name="event",
            field=models.ForeignKey(
                help_text="Event this activity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="event.event",
            ),
        ),
        migrations.AddField(
            model_name="eventactivity",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team associated with this activity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_activities",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="eventactivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User associated with this activity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                help_text="Users who can manage this event",
                limit_choices_to={"type": "organizer"},
                related_name="event_organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scoreboardentry",
            unique_together={("scoreboard", "team")},
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="eventpage",
            unique_together={("event", "slug")},
        ),
    ]
