# Generated by Django 4.2.7 on 2025-09-07 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("superadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User associated with this log entry (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="updated_by",
            field=models.ForeignKey(
                help_text="User who last updated the configuration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_config_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who scheduled this maintenance window",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_maintenance_windows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
