# Generated by Django 4.2.7 on 2025-09-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team the user belonged to at time of submission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="teams.team",
            ),
        ),
    ]
