# Generated by Django 4.2.7 on 2025-09-07 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("challenges", "0002_initial"),
        ("event", "0002_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                help_text="User who submitted the flag",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hintunlock",
            name="hint",
            field=models.ForeignKey(
                help_text="Hint that was unlocked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unlocks",
                to="challenges.hint",
            ),
        ),
        migrations.AddField(
            model_name="hintunlock",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team the user belonged to when unlocking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hint_unlocks",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="hintunlock",
            name="user",
            field=models.ForeignKey(
                help_text="User who unlocked the hint",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hint_unlocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hint",
            name="challenge",
            field=models.ForeignKey(
                help_text="Related challenge",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hints",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="flag",
            name="challenge",
            field=models.ForeignKey(
                help_text="Related challenge",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="challenge",
            field=models.ForeignKey(
                help_text="Related challenge",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_uploads",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="challenge",
            field=models.ForeignKey(
                help_text="The challenge this comment is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                help_text="User who created the comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challengefile",
            name="challenge",
            field=models.ForeignKey(
                help_text="Related challenge",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_files",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Challenge category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenges",
                to="challenges.challengecategory",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="event",
            field=models.ForeignKey(
                help_text="Event this challenge belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="event.event",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Challenges that must be solved before this one is visible",
                related_name="unlocks",
                to="challenges.challenge",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hintunlock",
            unique_together={("hint", "user")},
        ),
    ]
